/**
 * ESP Infinity
 * ESP WS2812b Infinity Mirror Protocol
 *
 * OpenAPI spec version: 0.0.1
 * Contact: yy@xxx.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Blender } from './blender';
import { Color } from './color';
import { Pattern } from './pattern';

export interface Hstripes extends Pattern { 
    color?: Color;
}