/**
 * ESP Infinity
 * ESP WS2812b Infinity Mirror Protocol
 *
 * OpenAPI spec version: 0.0.1
 * Contact: yy@xxx.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Blender } from './blender';

export interface Pattern { 
    pclass?: string;
    name?: string;
    speed?: number;
    hmirror?: boolean;
    vmirror?: boolean;
    rotate?: number;
    blender?: Blender;
}